background {
    monitor =
    path = ~/photos/wallpapers/1-osaka-jade-bg.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba({{colors.primary.default.hex_stripped}}ff)
    inner_color = rgba({{colors.background.default.hex_stripped}}ff)
    font_color = rgba({{colors.primary.default.hex_stripped}}ff)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba({{colors.primary.default.hex_stripped}}ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:30000] echo "$(cat /sys/class/power_supply/BAT1/status | grep -q Charging && echo '' || echo '') $(cat /sys/class/power_supply/BAT1/capacity)%"
    color = rgba({{colors.primary.default.hex_stripped}}ff)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, -180
    halign = center
    valign = top
}
