set -g status-style "bg=#{{colors.background.default.hex_stripped}},fg=#{{colors.primary.default.hex_stripped}}"
set -g status-left-style "fg=#{{colors.primary.default.hex_stripped}},bold"
set -g status-right-style "fg=#{{colors.secondary.default.hex_stripped}}"
set -g window-status-current-style "fg=#{{colors.background.default.hex_stripped}},bg=#{{colors.primary.default.hex_stripped}},bold"
set -g window-status-style "fg=#{{colors.primary.default.hex_stripped}}"
set -g pane-border-style "fg=#{{colors.surface_variant.default.hex_stripped}}"
set -g pane-active-border-style "fg=#{{colors.primary.default.hex_stripped}}"
set -g message-style "bg=#{{colors.surface_variant.default.hex_stripped}},fg=#{{colors.primary.default.hex_stripped}}"
