set -g status-style "bg=#0f1512,fg=#88d6ba"
set -g status-left-style "fg=#88d6ba,bold"
set -g status-right-style "fg=#b2ccc1"
set -g window-status-current-style "fg=#0f1512,bg=#88d6ba,bold"
set -g window-status-style "fg=#88d6ba"
set -g pane-border-style "fg=#3f4944"
set -g pane-active-border-style "fg=#88d6ba"
set -g message-style "bg=#3f4944,fg=#88d6ba"
