set -g status-style "bg=#181115,fg=#fbb0d7"
set -g status-left-style "fg=#fbb0d7,bold"
set -g status-right-style "fg=#dfbdcc"
set -g window-status-current-style "fg=#181115,bg=#fbb0d7,bold"
set -g window-status-style "fg=#fbb0d7"
set -g pane-border-style "fg=#504349"
set -g pane-active-border-style "fg=#fbb0d7"
set -g message-style "bg=#504349,fg=#fbb0d7"
