set -g status-style "bg=#19120c,fg=#fdb876"
set -g status-left-style "fg=#fdb876,bold"
set -g status-right-style "fg=#e2c0a4"
set -g window-status-current-style "fg=#19120c,bg=#fdb876,bold"
set -g window-status-style "fg=#fdb876"
set -g pane-border-style "fg=#51443a"
set -g pane-active-border-style "fg=#fdb876"
set -g message-style "bg=#51443a,fg=#fdb876"
