# Set prefix to Ctrl+Space (or keep Ctrl+b if you prefer)
set -g prefix C-Space
bind C-Space send-prefix
#Set status bar to top
set -g status-position top

set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Wayland clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
set -g set-clipboard on

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind -T root WheelUpPane
unbind -T root WheelDownPane

# Vim keybinds for navigation
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Split panes with more intuitive keys
bind v split-window -h
bind s split-window -v

# Source colors
source-file ~/.config/tmux/colors.conf
